CREATE TABLE "USER"
(
   ID              BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
   EMAIL           VARCHAR(50),
   PASSWORD        VARCHAR(250),
   FIRST_NAME      VARCHAR(20),
   LAST_NAME       VARCHAR(20),
   AGE             INTEGER,
   GENDER          INTEGER,
   CONSTRAINT      PK_USER PRIMARY KEY(ID)
);

CREATE TABLE DOCTOR
(
   ID              BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
   SPECIALITY_CODE VARCHAR(50),
   CREATE_TIME     TIMESTAMP,
   LAST_UPDATED    TIMESTAMP,
   USER_ID         BIGINT,
   CONSTRAINT      PK_DOCTOR  PRIMARY KEY(ID)
);

CREATE TABLE RX
(
   ID              BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
   USER_ID         BIGINT,
   DOCTOR_ID       BIGINT,
   SYMPTOMS        VARCHAR(250),
   MEDICINE        VARCHAR(250),  
   CREATE_TIME     TIMESTAMP,
   LAST_UPDATED    TIMESTAMP,
   CONSTRAINT  PK_RX  PRIMARY KEY(ID)
);